### PR TITLE
feat: checkpoint selecting strategy on sync-store getEvents

### PR DESCRIPTION
**Pull request by erensanlier**

### CODE REVIEW

**Comment by 0xOlias** [comment]
Hi @erensanlier, thanks for opening. This is a promising idea, but it's worth mentioning that on many apps, the `getEvents` query that we currently have performs well enough that the bottleneck during a fully sync indexing run is database round trips, not `getEvents` execution time. It's possible that going from 1 -> 4 queries might introduce a slowdown for some apps.

If you are able, could you provide a comment here including a before/after query plan?

**Comment by erensanlier** [comment]
Hey @0xOlias, sorry for not following up on this.

Opened this PR based on the idea of optimizing checkpoint selection in `getEvents`. Valid point that this implementation might slow down most apps. Possibly checkpoint selection might be added to the main query to address that concern.

Sharing the query plans for the following specific case:

`getEvents` tries to get 1000 events (ordered by checkpoint) from ponder_sync.logs table, which has +5M rows.

Query plan looks like this with the original query:
| QUERY PLAN |
| :--- |
| Limit  \(cost=518590.84..542595.53 rows=1001 width=3192\) |
|   -&gt;  Nested Loop Left Join  \(cost=518590.84..814105.15 rows=12323 width=3192\) |
|         -&gt;  Nested Loop Left Join  \(cost=518590.29..713330.23 rows=12323 width=1965\) |
|               -&gt;  Nested Loop  \(cost=518589.73..612904.50 rows=12323 width=1346\) |
|                     -&gt;  Gather Merge  \(cost=518589.18..520024.39 rows=12323 width=313\) |
|                           Workers Planned: 2 |
|                           -&gt;  Sort  \(cost=517589.15..517601.99 rows=5135 width=313\) |
|                                 Sort Key: "\*SELECT\* 1".checkpoint |
|                                 -&gt;  Parallel Append  \(cost=0.00..517272.68 rows=5135 width=313\) |
|                                       -&gt;  Subquery Scan on "\*SELECT\* 1"  \(cost=0.00..517272.68 rows=5135 width=313\) |
|                                             -&gt;  Nested Loop  \(cost=0.00..517221.33 rows=5135 width=345\) |
|                                                   Join Filter: \(\(\(\(logs\_1."chainId"\)::numeric = '10'::numeric\(16,0\)\) AND \(\(logs\_1.address\)::text = '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1'::text\) AND \(logs\_1."blockNumber" &gt;= '107087966'::numeric\) AND \(logs\_1."blockNumber" &lt;= '109400000'::numeric\) AND \("\*VALUES\*".column1 = 'log\_WLD\_Optimism\_optimism'::text\)\) OR \(\(\(logs\_1."chainId"\)::numeric = '1'::numeric\(16,0\)\) AND \(\(logs\_1.address\)::text = '0x163f8c2467924be0ae7b5347228cabf260318753'::text\) AND \(logs\_1."blockNumber" &gt;= '17714705'::numeric\) AND \("\*VALUES\*".column1 = 'log\_WLD\_Ethereum\_mainnet'::text\)\)\) |
|                                                   -&gt;  Parallel Seq Scan on logs logs\_1  \(cost=0.00..516478.78 rows=10242 width=340\) |
|                                                         Filter: \(\(\(checkpoint\)::text &gt; '169015438700000000000000100000000107277805000000000000000250000000000000058'::text\) AND \(\(checkpoint\)::text &lt;= '171589431500000000000000010000000019885172999999999999999999999999999999'::text\) AND \(\(topic0\)::text = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'::text\) AND \(\(\(\("chainId"\)::numeric = '10'::numeric\(16,0\)\) AND \(\(address\)::text = '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1'::text\) AND \("blockNumber" &gt;= '107087966'::numeric\) AND \("blockNumber" &lt;= '109400000'::numeric\)\) OR \(\(\("chainId"\)::numeric = '1'::numeric\(16,0\)\) AND \(\(address\)::text = '0x163f8c2467924be0ae7b5347228cabf260318753'::text\) AND \("blockNumber" &gt;= '17714705'::numeric\)\)\)\) |
|                                                   -&gt;  Values Scan on "\*VALUES\*"  \(cost=0.00..0.03 rows=1 width=32\) |
|                                                         Filter: \(\(column1 = 'log\_WLD\_Optimism\_optimism'::text\) OR \(column1 = 'log\_WLD\_Ethereum\_mainnet'::text\)\) |
|                     -&gt;  Index Scan using blocks\_pkey on blocks  \(cost=0.55..7.54 rows=1 width=1100\) |
|                           Index Cond: \(\(hash\)::text = \("\*SELECT\* 1"."blockHash"\)::text\) |
|               -&gt;  Index Scan using logs\_pkey on logs  \(cost=0.56..8.15 rows=1 width=690\) |
|                     Index Cond: \(id = "\*SELECT\* 1".log\_id\) |
|         -&gt;  Index Scan using transactions\_pkey on transactions  \(cost=0.56..8.18 rows=1 width=1294\) |
|               Index Cond: \(\(hash\)::text = \("\*SELECT\* 1"."transactionHash"\)::text\) |


When checkpoint is selected near the cursor:

| QUERY PLAN |
| :--- |
| Limit  \(cost=35.47..35.47 rows=1 width=3192\) |
|   -&gt;  Sort  \(cost=35.47..35.47 rows=1 width=3192\) |
|         Sort Key: "\*SELECT\* 1".checkpoint |
|         -&gt;  Nested Loop Left Join  \(cost=2.22..35.46 rows=1 width=3192\) |
|               -&gt;  Nested Loop Left Join  \(cost=1.67..26.88 rows=1 width=1965\) |
|                     -&gt;  Nested Loop  \(cost=1.11..18.31 rows=1 width=1346\) |
|                           -&gt;  Subquery Scan on "\*SELECT\* 1"  \(cost=0.56..9.74 rows=1 width=313\) |
|                                 -&gt;  Nested Loop  \(cost=0.56..9.73 rows=1 width=345\) |
|                                       Join Filter: \(\(\(\(logs\_1."chainId"\)::numeric = '10'::numeric\(16,0\)\) AND \(\(logs\_1.address\)::text = '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1'::text\) AND \(logs\_1."blockNumber" &gt;= '107087966'::numeric\) AND \(logs\_1."blockNumber" &lt;= '109400000'::numeric\) AND \("\*VALUES\*".column1 = 'log\_WLD\_Optimism\_optimism'::text\)\) OR \(\(\(logs\_1."chainId"\)::numeric = '1'::numeric\(16,0\)\) AND \(\(logs\_1.address\)::text = '0x163f8c2467924be0ae7b5347228cabf260318753'::text\) AND \(logs\_1."blockNumber" &gt;= '17714705'::numeric\) AND \("\*VALUES\*".column1 = 'log\_WLD\_Ethereum\_mainnet'::text\)\)\) |
|                                       -&gt;  Index Scan using logs\_checkpoint\_index on logs logs\_1  \(cost=0.56..9.66 rows=1 width=340\) |
|                                             Index Cond: \(\(\(checkpoint\)::text &gt; '169015438700000000000000100000000107277805000000000000000250000000000000058'::text\) AND \(\(checkpoint\)::text &lt;= '169015446100000000000000100000000107277842000000000000000250000000000000013'::text\)\) |
|                                             Filter: \(\(\(topic0\)::text = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'::text\) AND \(\(\(\("chainId"\)::numeric = '10'::numeric\(16,0\)\) AND \(\(address\)::text = '0xdc6ff44d5d932cbd77b52e5612ba0529dc6226f1'::text\) AND \("blockNumber" &gt;= '107087966'::numeric\) AND \("blockNumber" &lt;= '109400000'::numeric\)\) OR \(\(\("chainId"\)::numeric = '1'::numeric\(16,0\)\) AND \(\(address\)::text = '0x163f8c2467924be0ae7b5347228cabf260318753'::text\) AND \("blockNumber" &gt;= '17714705'::numeric\)\)\)\) |
|                                       -&gt;  Values Scan on "\*VALUES\*"  \(cost=0.00..0.03 rows=1 width=32\) |
|                                             Filter: \(\(column1 = 'log\_WLD\_Optimism\_optimism'::text\) OR \(column1 = 'log\_WLD\_Ethereum\_mainnet'::text\)\) |
|                           -&gt;  Index Scan using blocks\_pkey on blocks  \(cost=0.55..8.57 rows=1 width=1100\) |
|                                 Index Cond: \(\(hash\)::text = \("\*SELECT\* 1"."blockHash"\)::text\) |
|                     -&gt;  Index Scan using logs\_pkey on logs  \(cost=0.56..8.57 rows=1 width=690\) |
|                           Index Cond: \(id = "\*SELECT\* 1".log\_id\) |
|               -&gt;  Index Scan using transactions\_pkey on transactions  \(cost=0.56..8.57 rows=1 width=1294\) |
|                     Index Cond: \(\(hash\)::text = \("\*SELECT\* 1"."transactionHash"\)::text\) |

**Comment by 0xOlias** [comment]
Thanks, this is great. Seems pretty definitive. How could we add the checkpoint selection to the main query - additional CTEs perhaps?

Also while you're running this, I'd find it valuable to see the query plan for the logs checkpoint selection query.

**Comment by erensanlier** [comment]
Maybe this draft implementation is way to complicated. @0xOlias Would you be able to measure performance metrics if I implement just max checkpoint selection as a part of the main query? We can progress from there for additional optimizations.

**Comment by erensanlier** [comment]
With this implementation I couldn't spot any difference in performance for normal size apps. Almost 20x improvement in the query plan I mentioned above.

**Comment by 0xOlias** [comment]
Excellent work, the latest commit makes sense to me - very clever. Thinking through edge case conditions around the `max` and `coalesce` operators.

It would also be good to confirm that this works for SQLite.

**Comment by erensanlier** [comment]
@0xOlias don't really understand why SQLite check fails. Commit with exact same code (cde720333351ca046e7990c8cd04c0522927fd10) passed before. Would appreciate if you can look into it!

**Comment by 0xOlias** [comment]
Sure, I'll take care of SQLite.

Here's my understanding **when using `.offset(limit).limit(1)`** for the `log_checkpoints` query.

If there are more than `limit` rows in the `logs` table that have a checkpoint greater than our `fromCheckpoint`, the `log_checkpoints` table will have one row containing the `limit + 1`th checkpoint. We can safely use this value as an upper bound for the checkpoint in our overall `events` query.

| checkpoint  | 
| ------------- |
| '1690154387...'  | 

If there are fewer than `limit` rows in the `logs` table that have a checkpoint greater than our `fromCheckpoint`, the `log_checkpoints` table will have one row containing `null`. This means that there is no "hint" to be used, so we must fall back to the `toCheckpoint` in our overall `events` query.

| checkpoint  | 
| ------------- |
| null  | 

Now, we can apply the same logic for `blocks` and `callTraces`. The rule for composing these results is a simple `max`, excluding nulls (which is the default behavior for SQL `max`). If all of the hints are null, the `max` across them will be null, and we must fall back to the `toCheckpoint`. The `coalesce` function works great for that logic.

Continuing to mull over the specifics of the query construction, but this makes sense to me. Why did you choose to remove the offset approach in favor of a limit? It seems like that will lead to an unnecessarily large `all_checkpoints` table.

**Comment by erensanlier** [comment]
I was trying to understand why SQLite fails, because first time I have tried without `.offset` it passed the tests.

Would prefer using offset over limit.

**Comment by erensanlier** [comment]
@0xOlias ready for merge? need anything further from my side?

**Comment by sara554-beep** [comment]
Buen día a todos..
Necesito ayuda... tengo solo mi dirección de wallet.
Como recupero o puedo restaurar mi wallet que deje alojada o guarda en github.
Porfavor ayuda.

**Pull request merged**
